
from typing import Dict

random_baselines = {'Binary \n Majority' : 49.8, "Binary Majority \n Interleave" : 0, "Majority" : 4.1, "Sort" : 0, "Copy \n Unique" : 0, "Copy \n Repeat" : 0, "Parity" : 52.3, "Addition" : 0}

ape: Dict[str, Dict[str, float]] = {
    'binary_majority' : {
        'name' : 'Binary \n Majority',
        'Bin 0' : 100.0,
        'Bin 1' : 100.0,
        'Bin 2' : 100.0,
        'Type': 'Algorithm',
        'Expressive' : True,
        'ac0': False,
    },
    'binary_majority_interleave' : {
        'name' : 'Binary Majority \n Interleave',
        'Bin 0' : 100.0,
        'Bin 1' : 96.8,
        'Bin 2' : 84.7,
        'Type': 'Algorithm',
        'Expressive' : True,
        'ac0': False,
    },
    'majority' : {
        'name' : 'Majority',
        'Bin 0' : 100.0,
        'Bin 1' : 99.6,
        'Bin 2' : 97.8,
        'Type': 'Algorithm',
        'Expressive' : True,
        'ac0': False,
    },
    'sort': {
        'name': 'Sort',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 99.4,
        'Type': 'Algorithm',
        'Expressive' : True,
        'ac0': True,
    },
    'copy_unique': {
        'name': 'Copy \n Unique',
        'Bin 0': 100.0,
        'Bin 1': 99.9,
        'Bin 2': 98.7,
        'Type': 'Algorithm',
        'Expressive' : True,
        'ac0': True,
    },
    'copy_repeat': {
        'name': 'Copy \n Repeat',
        'Bin 0': 100.0,
        'Bin 1': 25.6,
        'Bin 2': 0,
        'Type': 'Algorithm',
        'Expressive' : False,
        'ac0': True,
    },
    'parity' : {
        'name' : 'Parity',
        'Bin 0' : 100.0,
        'Bin 1' : 83.0,
        'Bin 2' : 62.1,
        'Type': 'Algorithm',
        'Expressive' : False,
        'ac0': False,
    },
    'addition': {
        'name': 'Addition',
        'Bin 0': 99.7,
        'Bin 1': 26.8,
        'Bin 2': 0.0,
        'Type': 'Algorithm',
        'Expressive' : False,
        'ac0': True,
    },
    'd-2': {
        'name': 'D-2',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 2,
        'ac0': True
    },
    'd-3': {
        'name': 'D-3',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 3,
        'ac0': True,
    },
    'd-4': {
        'name': 'D-4',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 4,
        'ac0': True,
    },
    'd-12': {
        'name': 'D-12',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 12,
        'ac0': True,
    },
    'tomita1': {
        'name': 'Tomita 1',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 1,
        'ac0': True,
    },
    'tomita2': {
        'name': 'Tomita-2',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 1,
        'ac0': True,
    },
    'tomita4': {
        'name': 'Tomita-4',
        'Bin 0': 100.0,
        'Bin 1': 85.4,
        'Bin 2': 84.4,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 1,
        'ac0': True,
    },
    'tomita7': {
        'name': 'Tomita-7',
        'Bin 0': 100.0,
        'Bin 1': 94.2,
        'Bin 2': 93.2,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 1,
        'ac0': True,
    },    
    'aabbccddee': {
        'name': 'aa*bb*cc*dd*ee*',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 1,
        'ac0': True,
    },
    'adbc': {
        'name': '{a,b}*d{b,c}*',
        'Bin 0': 100.0,
        'Bin 1': 99.8,
        'Bin 2': 98.5,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 1,
        'ac0': True,
    },
    '012': {
        'name': '{0,1,2}*02*',
        'Bin 0': 99.7,
        'Bin 1': 24.4,
        'Bin 2': 1.2,
        'Type': 'Star Free',
        'Expressive' : False,
        'dot_depth': 2,
        'ac0': True,
    },
    '(aa)*': {
        'name': '(aa)*',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Non Star Free',
        'Expressive' : True,
        'ac0': True,
    },
    '(aaaa)*': {
        'name': '(aaaa)*',
        'Bin 0': 100.0,
        'Bin 1': 92.3,
        'Bin 2': 86.7,
        'Type': 'Non Star Free',
        'Expressive' : True,
        'ac0': True,
    },
    '(abab)*': {
        'name': '(abab)*',
        'Bin 0': 100.0,
        'Bin 1': 89.4,
        'Bin 2': 82.3,
        'Type': 'Non Star Free',
        'Expressive' : True,
        'ac0': True,
    },
    'tomita3': {
        'name': 'Tomita-3',
        'Bin 0': 60.45,
        'Bin 1': 7.7,
        'Bin 2': 0,
        'Type': 'Non Star Free',
        'Expressive' : False,
        'ac0': True,
    },
    'tomita5': {
        'name': 'Tomita-5',
        'Bin 0': 54.4,
        'Bin 1': 0,
        'Bin 2': 0,
        'Type': 'Non Star Free',
        'Expressive' : False,
        'ac0': False,
    },
    'tomita6': {
        'name': 'Tomita-6',
        'Bin 0': 59.6,
        'Bin 1': 0,
        'Bin 2': 0,
        'Type': 'Non Star Free',
        'Expressive' : False,
        'ac0': False,
    },
    'dyck1': {
        'name': 'Dyck 1',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Counter',
        'Expressive' : True
    },
    'shuffle2': {
        'name': 'Shuffle 2',
        'Bin 0': 85.9,
        'Bin 1': 82.2,
        'Bin 2': 50.4,
        'Type': 'Counter',
        'Expressive' : True
    },
    # 'shuffle4': {
    #     'name': 'Shuffle 4',
    #     'Bin 0': 76.4,
    #     'Bin 1': 43.2,
    #     'Bin 2': 12.1,
    #     'Type': 'Counter',
    #     'Expressive' : True
    # },
    # 'shuffle6': {
    #     'name': 'Shuffle 6',
    #     'Bin 0': 64.2,
    #     'Bin 1': 15.2,
    #     'Bin 2': 4.2,
    #     'Type': 'Counter',
    #     'Expressive' : True
    # },
    'anbn': {
        'name': 'AnBn',
        'Bin 0': 100.0,
        'Bin 1': 99.4,
        'Bin 2': 92.3,
        'Type': 'Counter',
        'Expressive' : True
    },
    'anbncn': {
        'name': 'AnBnCn',
        'Bin 0': 100.0,
        'Bin 1': 91.2,
        'Bin 2': 87.4,
        'Type': 'Counter',
        'Expressive' : True
    },
    'anbncndn': {
        'name': 'AnBnCnDn',
        'Bin 0': 100.0,
        'Bin 1': 86.4,
        'Bin 2': 75.2,
        'Type': 'Counter',
        'Expressive' : True
    },
    'bool3': {
        'name': 'Boolean 3',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Counter',
        'Expressive' : True
    },
    'bool5': {
        'name': 'Boolean 5',
        'Bin 0': 100.0,
        'Bin 1': 75.3,
        'Bin 2': 72.1,
        'Type': 'Counter',
        'Expressive' : True
    }
}

nope: Dict[str, Dict[str, float]] = {
    'binary_majority' : {
        'name' : 'Binary \n Majority',
        'Bin 0' : 100.0,
        'Bin 1' : 100.0,
        'Bin 2' : 100.0,
        'Type': 'Algorithm',
        'Expressive' : True,
        'ac0': False,
    },
    'binary_majority_interleave' : {
        'name' : 'Binary Majority \n Interleave',
        'Bin 0' : 96.2,
        'Bin 1' : 68.8,
        'Bin 2' : 39.5,
        'Type': 'Algorithm',
        'Expressive' : False,
        'ac0': False,
    },
    'majority' : {
        'name' : 'Majority',
        'Bin 0' : 100.0,
        'Bin 1' : 99.9,
        'Bin 2' : 98.5,
        'Type': 'Algorithm',
        'Expressive' : True,
        'ac0': False,
    },
    'sort': {
        'name': 'Sort',
        'Bin 0': 100.0,
        'Bin 1': 99.8,
        'Bin 2': 80.6,
        'Type': 'Algorithm',
        'Expressive' : True,
        'ac0': True,
    },
    'copy_unique': {
        'name': 'Copy \n Unique',
        'Bin 0': 100.0,
        'Bin 1': 18.0,
        'Bin 2': 0,
        'Type': 'Algorithm',
        'Expressive' : False,
        'ac0': True,
    },
    'copy_repeat': {
        'name': 'Copy \n Repeat',
        'Bin 0': 100.0,
        'Bin 1': 28.0,
        'Bin 2': 0,
        'Type': 'Algorithm',
        'Expressive' : False,
        'ac0': True,
    },
    'parity': {
        'name': 'Parity',
        'Bin 0': 97.5,
        'Bin 1': 74.5,
        'Bin 2': 63.3,
        'Type': 'Algorithm',
        'Expressive' : False,
        'ac0': False,
    },
    'addition': {
        'name': 'Addition',
        'Bin 0': 99.5,
        'Bin 1': 27.7,
        'Bin 2': 0,
        'Type': 'Algorithm',
        'Expressive' : False,
        'ac0': True,
    },
    'd-2': {
        'name': 'D-2',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 2,
        'ac0': True,
    },
    'd-3': {
        'name': 'D-3',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 3,
        'ac0': True,
    },
    'd-4': {
        'name': 'D-4',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 4,
        'ac0': True,
    },
    'd-12': {
        'name': 'D-12',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 12,
        'ac0': True,
    },
    'tomita1': {
        'name': 'Tomita 1',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 1,
        'ac0': True,
    },
    'tomita2': {
        'name': 'Tomita-2',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 1,
        'ac0': True,
    },
    'tomita4': {
        'name': 'Tomita-4',
        'Bin 0': 100.0,
        'Bin 1': 16.45,
        'Bin 2': 0,
        'Type': 'Star Free',
        'Expressive' : False,
        'dot_depth': 1,
        'ac0': True,
    },
    'tomita7': {
        'name': 'Tomita-7',
        'Bin 0': 100.0,
        'Bin 1': 87.5,
        'Bin 2': 76.2,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 1,
        'ac0': True,
    },    
    'aabbccddee': {
        'name': 'aa*bb*cc*dd*ee*',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 1,
        'ac0': True,
    },
    'adbc': {
        'name': '{a,b}*d{b,c}*',
        'Bin 0': 100.0,
        'Bin 1': 99.8,
        'Bin 2': 98.5,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 1,
        'ac0': True,
    },
    '012': {
        'name': '{0,1,2}*02*',
        'Bin 0': 18.2,
        'Bin 1': 11.2,
        'Bin 2': 0,
        'Type': 'Star Free',
        'Expressive' : False,
        'dot_depth': 2,
        'ac0': True,
    },      
    '(aa)*': {
        'name': '(aa)*',
        'Bin 0': 100.0,
        'Bin 1': 0,
        'Bin 2': 0,
        'Type': 'Non Star Free',
        'Expressive' : False,
        'ac0': True,
    },
    '(aaaa)*': {
        'name': '(aaaa)*',
        'Bin 0': 100.0,
        'Bin 1': 0,
        'Bin 2': 0,
        'Type': 'Non Star Free',
        'Expressive' : False,
        'ac0': True,
    },
    '(abab)*': {
        'name': '(abab)*',
        'Bin 0': 100.0,
        'Bin 1': 0,
        'Bin 2': 0,
        'Type': 'Non Star Free',
        'Expressive' : False,
        'ac0': True,
    },
    'tomita3': {
        'name': 'Tomita-3',
        'Bin 0': 21.1,
        'Bin 1': 0,
        'Bin 2': 0,
        'Type': 'Non Star Free',
        'Expressive' : False,
        'ac0': True,
    },
    'tomita5': {
        'name': 'Tomita-5',
        'Bin 0': 7.1,
        'Bin 1': 0,
        'Bin 2': 0,
        'Type': 'Non Star Free',
        'Expressive' : False,
        'ac0': False,
    },
    'tomita6': {
        'name': 'Tomita-6',
        'Bin 0': 2.4,
        'Bin 1': 0,
        'Bin 2': 0,
        'Type': 'Non Star Free',
        'Expressive' : False,
        'ac0': False,
    },
    'dyck1': {
        'name': 'Dyck 1',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Counter',
        'Expressive' : True
    },
    'shuffle2': {
        'name': 'Shuffle 2',
        'Bin 0': 81.2,
        'Bin 1': 79.8,
        'Bin 2': 42.7,
        'Type': 'Counter',
        'Expressive' : True
    },
    # 'shuffle4': {
    #     'name': 'Shuffle 4',
    #     'Bin 0': 0,
    #     'Bin 1': 0,
    #     'Bin 2': 0,
    #     'Type': 'Counter',
    #     'Expressive' : True
    # },
    # 'shuffle6': {
    #     'name': 'Shuffle 6',
    #     'Bin 0': 0,
    #     'Bin 1': 0,
    #     'Bin 2': 0,
    #     'Type': 'Counter',
    #     'Expressive' : True
    # },
    'anbn': {
        'name': 'AnBn',
        'Bin 0': 100.0,
        'Bin 1': 100,
        'Bin 2': 100,
        'Type': 'Counter',
        'Expressive' : True
    },
    'anbncn': {
        'name': 'AnBnCn',
        'Bin 0': 100.0,
        'Bin 1': 100,
        'Bin 2': 100,
        'Type': 'Counter',
        'Expressive' : True
    },
    'anbncndn': {
        'name': 'AnBnCnDn',
        'Bin 0': 100.0,
        'Bin 1': 100,
        'Bin 2': 100,
        'Type': 'Counter',
        'Expressive' : True
    },
    'bool3': {
        'name': 'Boolean 3',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Counter',
        'Expressive' : True
    },
    'bool5': {
        'name': 'Boolean 5',
        'Bin 0': 100.0,
        'Bin 1': 75.3,
        'Bin 2': 72.1,
        'Type': 'Counter',
        'Expressive' : True
    }         
}
reg: Dict[str, Dict[str, float]] = {
    'binary_majority' : {
        'name' : 'Binary \n Majority',
        'Bin 0' : 100.0,
        'Bin 1' : 100.0,
        'Bin 2' : 99.9,
        'Type': 'Algorithm',
        'Expressive' : True,
        'ac0': False,
    },
    'binary_majority_interleave' : {
        'name' : 'Binary Majority \n Interleave',
        'Bin 0' : 100.0,
        'Bin 1' : 97.3,
        'Bin 2' : 86.2,
        'Type': 'Algorithm',
        'Expressive' : False,
        'ac0': False,
    },
    'majority' : {
        'name' : 'Majority',
        'Bin 0' : 100.0,
        'Bin 1' : 99.9,
        'Bin 2' : 99.0,
        'Type': 'Algorithm',
        'Expressive' : True,
        'ac0': False,
    },
    'sort': {
        'name': 'Sort',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 99.6,
        'Type': 'Algorithm',
        'Expressive' : True,
        'ac0': True,
    },
    'copy_unique': {
        'name': 'Copy \n Unique',
        'Bin 0': 100.0,
        'Bin 1': 99.8,
        'Bin 2': 99.3,
        'Type': 'Algorithm',
        'Expressive' : False,
        'ac0': True,
    },
    'copy_repeat': {
        'name': 'Copy \n Repeat',
        'Bin 0': 100.0,
        'Bin 1': 25.1,
        'Bin 2': 0,
        'Type': 'Algorithm',
        'Expressive' : False,
        'ac0': True,
    },
    'parity': {
        'name': 'Parity',
        'Bin 0': 97.5,
        'Bin 1': 83.4,
        'Bin 2': 64.2,
        'Type': 'Algorithm',
        'Expressive' : False,
        'ac0': False,
    },
    'addition': {
        'name': 'Addition',
        'Bin 0': 99.8,
        'Bin 1': 25.8,
        'Bin 2': 0,
        'Type': 'Algorithm',
        'Expressive' : False,
        'ac0': True,
    },
    'd-2': {
        'name': 'D-2',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 2,
        'ac0': True,
    },
    'd-3': {
        'name': 'D-3',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 3,
        'ac0': True,
    },
    'd-4': {
        'name': 'D-4',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 4,
        'ac0': True,
    },
    'd-12': {
        'name': 'D-12',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 12,
        'ac0': True,
    },
    'tomita1': {
        'name': 'Tomita 1',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 1,
        'ac0': True,
    },
    'tomita2': {
        'name': 'Tomita-2',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 1,
        'ac0': True,
    },
    'tomita4': {
        'name': 'Tomita-4',
        'Bin 0': 100.0,
        'Bin 1': 81.3,
        'Bin 2': 79.3,
        'Type': 'Star Free',
        'Expressive' : False,
        'dot_depth': 1,
        'ac0': True,
    },
    'tomita7': {
        'name': 'Tomita-7',
        'Bin 0': 100.0,
        'Bin 1': 91.2,
        'Bin 2': 90.9,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 1,
        'ac0': True,
    },    
    'aabbccddee': {
        'name': 'aa*bb*cc*dd*ee*',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 1,
        'ac0': True,
    },
    'adbc': {
        'name': '{a,b}*d{b,c}*',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Star Free',
        'Expressive' : True,
        'dot_depth': 1,
        'ac0': True,
    },
    '012': {
        'name': '{0,1,2}*02*',
        'Bin 0': 99.6,
        'Bin 1': 25.6,
        'Bin 2': 2.1,
        'Type': 'Star Free',
        'Expressive' : False,
        'dot_depth': 2,
        'ac0': True,
    },      
    '(aa)*': {
        'name': '(aa)*',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Non Star Free',
        'Expressive' : False,
        'ac0': True,
    },
    '(aaaa)*': {
        'name': '(aaaa)*',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Non Star Free',
        'Expressive' : False,
        'ac0': True,
    },
    '(abab)*': {
        'name': '(abab)*',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Non Star Free',
        'Expressive' : False,
        'ac0': True,
    },
    'tomita3': {
        'name': 'Tomita-3',
        'Bin 0': 57.1,
        'Bin 1': 6.9,
        'Bin 2': 0,
        'Type': 'Non Star Free',
        'Expressive' : False,
        'ac0': True,
    },
    'tomita5': {
        'name': 'Tomita-5',
        'Bin 0': 52.1,
        'Bin 1': 0,
        'Bin 2': 0,
        'Type': 'Non Star Free',
        'Expressive' : False,
        'ac0': False,
    },
    'tomita6': {
        'name': 'Tomita-6',
        'Bin 0': 58.6,
        'Bin 1': 0,
        'Bin 2': 0,
        'Type': 'Non Star Free',
        'Expressive' : False,
        'ac0': False,
    },
    'dyck1': {
        'name': 'Dyck 1',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Counter',
        'Expressive' : True
    },
    'shuffle2': {
        'name': 'Shuffle 2',
        'Bin 0': 81.2,
        'Bin 1': 79.8,
        'Bin 2': 42.7,
        'Type': 'Counter',
        'Expressive' : True
    },
    # 'shuffle4': {
    #     'name': 'Shuffle 4',
    #     'Bin 0': 0,
    #     'Bin 1': 0,
    #     'Bin 2': 0,
    #     'Type': 'Counter',
    #     'Expressive' : True
    # },
    # 'shuffle6': {
    #     'name': 'Shuffle 6',
    #     'Bin 0': 0,
    #     'Bin 1': 0,
    #     'Bin 2': 0,
    #     'Type': 'Counter',
    #     'Expressive' : True
    # },
    'anbn': {
        'name': 'AnBn',
        'Bin 0': 100.0,
        'Bin 1': 100,
        'Bin 2': 100,
        'Type': 'Counter',
        'Expressive' : True
    },
    'anbncn': {
        'name': 'AnBnCn',
        'Bin 0': 100.0,
        'Bin 1': 100,
        'Bin 2': 100,
        'Type': 'Counter',
        'Expressive' : True
    },
    'anbncndn': {
        'name': 'AnBnCnDn',
        'Bin 0': 100.0,
        'Bin 1': 100,
        'Bin 2': 100,
        'Type': 'Counter',
        'Expressive' : True
    },
    'bool3': {
        'name': 'Boolean 3',
        'Bin 0': 100.0,
        'Bin 1': 100.0,
        'Bin 2': 100.0,
        'Type': 'Counter',
        'Expressive' : True
    },
    'bool5': {
        'name': 'Boolean 5',
        'Bin 0': 100.0,
        'Bin 1': 75.3,
        'Bin 2': 72.1,
        'Type': 'Counter',
        'Expressive' : True
    }         
}
