name: D-2
lang_fam: StarFree
batch_size: 32
multiple: True
chunk_size: 2
unique: False
num_val_bins: 3
lower_window: 2
upper_window: 50
len_incr: 50
training_size: 200
test_size: 25
lang_class: D_n
num_par: 2